import React from "react";
import { SEO } from "../components/SEO";
import { motion } from "motion/react";

export const Terms = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
      <SEO 
        title="Terms of Service - Zyven AI" 
        description="Read Zyven AI's terms of service to understand the rules and guidelines for using our free AI tools and services."
        canonical="/terms"
      />

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-16"
      >
        <h1 className="text-4xl md:text-6xl font-bold mb-6 tracking-tight">
          Terms of Service
        </h1>
        <p className="text-lg text-white/50 leading-relaxed max-w-2xl">
          Last updated: March 23, 2026. By using Zyven AI, you agree to these terms.
        </p>
      </motion.div>

      <div className="prose prose-invert max-w-none space-y-12">
        <section>
          <h2 className="text-2xl font-bold mb-4">1. Acceptance of Terms</h2>
          <p className="text-white/60 leading-relaxed">
            By accessing or using Zyven AI, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4">2. Use License</h2>
          <p className="text-white/60 leading-relaxed">
            Permission is granted to use Zyven AI's tools for personal or commercial content creation. This is the grant of a license, not a transfer of title, and under this license you may not:
          </p>
          <ul className="list-disc pl-6 text-white/60 space-y-2">
            <li>Use the tools for any illegal or harmful purpose.</li>
            <li>Attempt to decompile or reverse engineer any software contained on Zyven AI.</li>
            <li>Use automated scripts or bots to scrape or abuse our services.</li>
            <li>Remove any copyright or other proprietary notations from the materials.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4">3. Disclaimer</h2>
          <p className="text-white/60 leading-relaxed">
            The materials on Zyven AI are provided on an 'as is' basis. Zyven AI makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4">4. Limitations</h2>
          <p className="text-white/60 leading-relaxed">
            In no event shall Zyven AI or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Zyven AI.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4">5. Content Accuracy</h2>
          <p className="text-white/60 leading-relaxed">
            AI-generated content may sometimes be inaccurate or biased. Users are responsible for reviewing and verifying any content generated by Zyven AI before use.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold mb-4">6. Governing Law</h2>
          <p className="text-white/60 leading-relaxed">
            These terms and conditions are governed by and construed in accordance with the laws of your jurisdiction and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.
          </p>
        </section>
      </div>
    </div>
  );
};
